# Generated by Django 6.1 on 2026-08-31 13:03

from django.db import migrations

def populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.create(
        name='Buddy',
        date_of_birth='2018-09-12',
        personal_photo='https://joyrideharness.com/cdn/shop/articles/AdobeStock_274099078.jpg?v=1620400547'
    )

def reverse_populate_pet_model(apps, schema_editor):
    PetModel = apps.get_model('pets', 'Pet')
    PetModel.objects.filter(
        name='Buddy',
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=populate_pet_model, reverse_code=reverse_populate_pet_model),
    ]
