# Generated by Django 6.1 on 2026-08-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
    ]
